---
kind: Namespace
apiVersion: v1
metadata:
  name: mailpit
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: mailpit
  labels:
    app.kubernetes.io/instance: mailpit
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/service: mailpit
spec:
  type: ClusterIP
  ports:
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: http
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
  selector:
    app.kubernetes.io/component: mailpit
    app.kubernetes.io/instance: mailpit
    app.kubernetes.io/name: mailpit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: mailpit
  labels:
    app.kubernetes.io/component: mailpit
    app.kubernetes.io/instance: mailpit
    app.kubernetes.io/name: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mailpit
      app.kubernetes.io/name: mailpit
      app.kubernetes.io/instance: mailpit
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mailpit
        app.kubernetes.io/instance: mailpit
        app.kubernetes.io/name: mailpit
    spec:
      containers:
        - env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: MP_SMTP_AUTH_ACCEPT_ANY
              value: "1"
            - name: MP_SMTP_AUTH_ALLOW_INSECURE
              value: "1"
          name: mailpit
          image: ghcr.io/axllent/mailpit:v1.28.3
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mailpit
  namespace: mailpit
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
    - "mailpit.bitey.life"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mailpit
          port: 8025
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mailpit-private
  namespace: mailpit
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: mailpit.bitey.life
      recordType: CNAME
      targets:
        - intgw.bitey.life
# ---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: mailpit-public
#   namespace: mailpit
#   annotations:
#     external-dns.custom/type: public
# spec:
#   endpoints:
#     - dnsName: mailpit.bitey.life
#       recordType: CNAME
#       targets:
#         - ingress.bitey.life
#       providerSpecific:
#         - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
#           value: "true"