---
kind: Namespace
apiVersion: v1
metadata:
  name: opentelemetry-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-operator
    targetRevision: 0.90.4
    helm:
      valuesObject:
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-k8s
        admissionWebhooks:
          certManager:
            enabled: false
          autoGenerateCert:
            enabled: true