apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 80.6.0
    helm:
      valuesObject:
        grafana:
          enabled: false
        kubeApiServer:
          enabled: true
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        prometheus:
          prometheusSpec:
            retention: 1d
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ClientSideApplyMigration=false
    automated: {}
    #   allowEmpty: true
    #   prune: true
    #   selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.49.0
    helm:
      valuesObject:
        deploymentMode: SingleBinary
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          compactor:
            working_directory: /var/loki/compactor/retention
            delete_request_store: filesystem
            retention_enabled: true
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: "filesystem"
          limits_config:
            retention_period: 14d
        singleBinary:
          replicas: 1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ClientSideApplyMigration=false
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: fluent-bit
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.54.0
    helm:
      valuesObject:
        config:
          outputs: |
            [OUTPUT]
                name                   loki
                match                  *
                host                   loki-gateway.observability.svc.cluster.local
                port                   80
                labels                 job=fluentbit
                auto_kubernetes_labels on
  syncPolicy:
    syncOptions:
      - ClientSideApplyMigration=false
      - ServerSideApply=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
