---
kind: Namespace
apiVersion: v1
metadata:
  name: observability
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso
  namespace: observability
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: grafana_client_id
      remoteRef:
        key: sso
        property: grafana_client_id
    - secretKey: grafana_client_secret
      remoteRef:
        key: sso
        property: grafana_client_secret
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.4.2
    helm:
      valuesObject:
        adminUser: admin
        plugins:
          # https://github.com/Altinity/clickhouse-grafana
          - vertamedia-clickhouse-datasource
          # https://github.com/grafana/clickhouse-datasource
          - grafana-clickhouse-datasource
        datasources:
          datasources.yaml:
            apiVersion: 1
            deleteDatasources:
              - { name: Alertmanager, orgId: 1 }
              - { name: Loki, orgId: 1 }
              - { name: Prometheus, orgId: 1 }
            datasources:
              - name: Prometheus
                type: prometheus
                uid: prometheus
                access: proxy
                url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
                isDefault: true
              - name: Loki
                type: loki
                uid: loki
                access: proxy
                url: http://loki-gateway.observability.svc.cluster.local
                jsonData:
                  maxLines: 250
        env:
          GF_SERVER_ROOT_URL: "https://grafana.bitey.life"
          GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
          GF_AUTH_DISABLE_LOGIN_FORM: "true"
          GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
          GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email offline_access"
          GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.bitey.life/application/o/authorize/"
          GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.bitey.life/application/o/token/"
          GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.bitey.life/application/o/userinfo/"
          GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'Grafana Admin') && 'Admin' || 'Viewer'"
        envValueFrom:
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
            secretKeyRef:
              key: grafana_client_id
              name: sso
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
            secretKeyRef:
              key: grafana_client_secret
              name: sso
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: observability
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
    - "grafana.bitey.life"
  rules:
    - backendRefs:
        - name: grafana
          port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: grafana
  namespace: observability
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: grafana.bitey.life
      recordType: CNAME
      targets:
        - intgw.bitey.life
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-passwords
  namespace: observability
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: uuid
      rewrite:
        - regexp:
            source: uuid
            target: collector
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: uuid
      rewrite:
        - regexp:
            source: uuid
            target: grafana
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: observability
spec:
  configuration:
    settings:
      logger/size: "500M"
      logger/count: 1
    clusters:
      - name: otel-cluster
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-pod-template
    users:
      collector/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-passwords
            key: collector
      collector/networks/ip: "::/0"
      collector/grants/query:
        - GRANT SELECT, INSERT, UPDATE, DROP, DELETE, ALTER, CREATE ON otel.*
        - GRANT CREATE DATABASE ON *.*
      grafana/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-passwords
            key: grafana
      grafana/networks/ip: "::/0"
      grafana/grants/query:
        - GRANT SELECT ON otel.*
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              env:
                - name: CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS
                  value: "true"
              volumeMounts:
                - name: bootstrap-configmap-volume
                  mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: bootstrap-configmap-volume
              configMap:
                name: bootstrap-mounted-configmap
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  mode: daemonset
  env:
    - name: CLICKHOUSE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: clickhouse-passwords
          key: collector
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    exporters:
      debug:
        verbosity: detailed
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/README.md#example-config
      clickhouse:
        endpoint: tcp://clickhouse-clickhouse.observability.svc.cluster.local:9000?dial_timeout=10s&compress=lz4&async_insert=1
        username: collector
        password: ${env:CLICKHOUSE_PASSWORD}
        ttl: 168h # a week
        create_schema: true
        timeout: 5s
        database: otel
        sending_queue:
          queue_size: 1000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [clickhouse]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [clickhouse]
        logs:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [clickhouse]