---
kind: Namespace
apiVersion: v1
metadata:
  name: argocd
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: sso
        property: argocd_client_id
    - secretKey: client_secret
      remoteRef:
        key: sso
        property: argocd_client_secret
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.0.1
    helm:
      valuesObject:
        configs:
          params:
            server.insecure: true
          cm:
            resource.compareoptions: |
              ignoreAggregatedRoles: true
              ignoreResourceStatusField: crd
            url: "https://argocd.bitey.life"
            dex.config: |
              connectors:
                - type: oidc
                  name: authentik
                  id: authentik
                  config:
                    issuer: https://auth.bitey.life/application/o/argocd/
                    clientID: $sso:client_id
                    clientSecret: $sso:client_secret
                    insecureEnableGroups: true
                    scopes:
                      - openid
                      - profile
                      - email
          rbac:
            policy.csv: |
              g, ArgoCD Admin, role:admin
        repoServer:
          rbac:
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get", "watch", "list"]
          deploymentAnnotations:
            reloader.stakater.com/auto: "true"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - name: "*"
      namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pineapp-homelab
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/acelinkio/argocd-homelab.git
        revision: HEAD
        files:
          - path: pineapp/**/manifest.yaml
  template:
    metadata:
      name: '{{.path.basename}}.manifest'
    spec:
      project: homelab
      source:
        repoURL: https://github.com/acelinkio/argocd-homelab.git
        path: '{{ .path.path }}'
        targetRevision: HEAD
        directory:
          recurse: false
          include: "{manifest.yaml}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
  hostnames:
    - "argocd.bitey.life"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
---
# apiVersion: gateway.networking.k8s.io/v1
# kind: GRPCRoute
# metadata:
#   name: argocd
#   namespace: argocd
# spec:
#   parentRefs:
#   - name: internal
#     namespace: gateway
#     sectionName: https
#   hostnames:
#   - "argocd.bitey.life"
#   rules:
#   - backendRefs:
#     - name: argocd-server
#       port: 80
# ---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: argocd-private
  namespace: argocd
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: argocd.bitey.life
      recordType: CNAME
      targets:
        - intgw.bitey.life
---
## Private Repository Secret example
## https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/
# apiVersion: v1
# kind: Secret
# metadata:
#   name: github
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repo-creds
# type: Opaque
# stringData:
#   password: github_pat_xxxxxxxx
#   url:  https://github.com/xxxxxxxx/argocd-homelab.git
#   username: xxxxxxxx
#   type: git
