kind: Namespace
apiVersion: v1
metadata:
  name: 1passwordconnect
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1passwordconnect
  namespace: argocd
spec:
  destination:
    namespace: 1passwordconnect
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.13.0
    helm:
      values: |
        connect:
          credentialsName: 1passwordconnect
          credentialsKey: 1password-credentials.json
          serviceType: ClusterIP
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
