## Goal is to only initially deploy argocd with minimal configurations
## Once deployed, argocd can manage itself
## https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd
kind: Namespace
apiVersion: v1
metadata:
  name: argocd
