kind: Namespace
apiVersion: v1
metadata:
  name: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.3
    helm:
      values: |
        installCRDs: "true"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
