kind: Namespace
apiVersion: v1
metadata:
  name: gateway-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatewayapi
  namespace: argocd
spec:
  destination:
    namespace: gateway-system
    
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/acelinkio/empty.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          # $ must be escaped with by $$
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.1/standard-install.yaml
            patches:
              - target:
                  kind: Namespace
                patch: |
                  $$patch: delete
                  kind: Namespace
                  metadata:
                    name: deletethis