kind: Namespace
apiVersion: v1
metadata:
  name: gpu-operator
---
# IMPORTANT NOTE: configuration requires knowledge of node cri
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
spec:
  destination:
    namespace: gpu-operator
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v23.9.1
    helm:
      valuesObject:
        driver:
          enabled: 'false'
        toolkit:
          env:
            - name: CONTAINERD_CONFIG
              value: /etc/containerd/config.toml
            - name: CONTAINERD_SOCKET
              value: /run/k3s/containerd/containerd.sock
            - name: CONTAINERD_RUNTIME_CLASS
              value: nvidia
            - name: CONTAINERD_SET_AS_DEFAULT
              value: 'true'
        devicePlugin:
          config:
            create: true
            name: time-slicing-config
            default: any
            data:
              any: |-
                version: v1
                flags:
                  migStrategy: none
                sharing:
                  timeSlicing:
                    renameByDefault: false
                    failRequestsGreaterThanOne: false
                    resources:
                      - name: nvidia.com/gpu
                        replicas: 4
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
