kind: Namespace
apiVersion: v1
metadata:
  name: knative-serving
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  destination:
    namespace: knative-serving
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/acelinkio/empty.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          # $ must be escaped with by $$
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-core.yaml
            patches:
              - target:
                  kind: Namespace
                patch: |
                  $$patch: delete
                  kind: Namespace
                  metadata:
                    name: deletethis
              - target:
                  kind: MutatingWebhookConfiguration
                patch: |
                  - op: replace
                    path: /webhooks/0/rules/0/apiVersions/0
                    value: v1alpha1
              - target:
                  kind: MutatingWebhookConfiguration
                patch: |
                  - op: add
                    path: /webhooks/0/rules/0/apiVersions/1
                    value: v1
              - target:
                  kind: MutatingWebhookConfiguration
                patch: |
                  - op: add
                    path: /webhooks/0/rules/0/apiVersions/1
                    value: v1beta1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true