kind: Namespace
apiVersion: v1
metadata:
  name: knative-serving
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  destination:
    namespace: knative-serving
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          value: |-
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
            - https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-core.yaml
            patches:
            - target:
                kind: Namespace
              patch: |-
                $patch: delete
                kind: Namespace
                metadata:
                  name: deletethis
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true