kind: Namespace
apiVersion: v1
metadata:
  name: knative-serving
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  destination:
    namespace: knative-serving
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/acelinkio/empty.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          # $ must be escaped with by $$
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-core.yaml
            patches:
              - target:
                  kind: Namespace
                patch: |
                  $$patch: delete
                  kind: Namespace
                  metadata:
                    name: deletethis
              - target:
                  kind: MutatingWebhookConfiguration
                patch: |
                  $$patch: merge
                  kind: MutatingWebhookConfiguration
                  metadata:
                    name: webhook.serving.knative.dev
                  webhooks:
                  - admissionReviewVersions: ["v1", "v1beta1"]
                    clientConfig:
                      service:
                        name: webhook
                        namespace: knative-serving
                    failurePolicy: Fail
                    sideEffects: None
                    name: webhook.serving.knative.dev
                    timeoutSeconds: 10
                    rules:
                      - apiGroups:
                          - autoscaling.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - metrics
                          - metrics/status
                        scope: '*'
                      - apiGroups:
                          - autoscaling.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - podautoscalers
                          - podautoscalers/status
                        scope: '*'
                      - apiGroups:
                          - networking.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - certificates
                          - certificates/status
                        scope: '*'
                      - apiGroups:
                          - networking.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - ingresses
                          - ingresses/status
                        scope: '*'
                      - apiGroups:
                          - networking.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - serverlessservices
                          - serverlessservices/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - configurations
                          - configurations/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - revisions
                          - revisions/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - routes
                          - routes/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - services
                          - services/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - domainmappings
                          - domainmappings/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1beta1
                        operations:
                          - CREATE
                          - UPDATE
                        resources:
                          - domainmappings
                          - domainmappings/status
                        scope: '*'
              - target:
                  kind: ValidatingWebhookConfiguration
                  name: validation.webhook.serving.knative.dev
                patch: |
                  $$patch: merge
                  kind: ValidatingWebhookConfiguration
                  metadata:
                    name: validation.webhook.serving.knative.dev
                  webhooks:
                  - admissionReviewVersions:
                      - v1
                      - v1beta1
                    clientConfig:
                      service:
                        name: webhook
                        namespace: knative-serving
                    failurePolicy: Fail
                    sideEffects: None
                    name: validation.webhook.serving.knative.dev
                    timeoutSeconds: 10
                    rules:
                      - apiGroups:
                          - autoscaling.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - metrics
                          - metrics/status
                        scope: '*'
                      - apiGroups:
                          - autoscaling.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - podautoscalers
                          - podautoscalers/status
                        scope: '*'
                      - apiGroups:
                          - networking.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - certificates
                          - certificates/status
                        scope: '*'
                      - apiGroups:
                          - networking.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - ingresses
                          - ingresses/status
                        scope: '*'
                      - apiGroups:
                          - networking.internal.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - serverlessservices
                          - serverlessservices/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - configurations
                          - configurations/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - revisions
                          - revisions/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - routes
                          - routes/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - services
                          - services/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1alpha1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - domainmappings
                          - domainmappings/status
                        scope: '*'
                      - apiGroups:
                          - serving.knative.dev
                        apiVersions:
                          - v1beta1
                        operations:
                          - CREATE
                          - UPDATE
                          - DELETE
                        resources:
                          - domainmappings
                          - domainmappings/status
                        scope: '*'
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true