kind: Namespace
apiVersion: v1
metadata:
  name: knative-serving
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  destination:
    namespace: knative-serving
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/acelinkio/empty.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          # $ must be escaped with by $$
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-core.yaml
            patches:
              - target:
                  kind: Namespace
                patch: |
                  $$patch: delete
                  kind: Namespace
                  metadata:
                    name: deletethis
              - target:
                  kind: MutatingWebhookConfiguration
                patch: |
                  $$patch: merge
                  kind: MutatingWebhookConfiguration
                  metadata:
                    name: webhook.serving.knative.dev
                  webhooks:
                  - admissionReviewVersions: ["v1", "v1beta1"]
                    clientConfig:
                      service:
                        name: webhook
                        namespace: knative-serving
                    failurePolicy: Fail
                    sideEffects: None
                    name: webhook.serving.knative.dev
                    timeoutSeconds: 10
                    rules:
                    - apiGroups:
                      - serving.knative.dev
                      apiVersions:
                      - v1beta1
                      - v1alpha1
                      - v1
                      operations:
                      - CREATE
                      - UPDATE
                      scope: "*"
                      resources:
                      - configurations
                      - configurations/status
                      - revisions
                      - revisions/status
                      - routes
                      - routes/status
                      - services
                      - services/status
                      - domainmappings
                      - domainmappings/status
                    - apiGroups:
                      - networking.internal.knative.dev
                      apiVersions:
                      - v1alpha1
                      operations:
                      - CREATE
                      - UPDATE
                      scope: "*"
                      resources:
                      - certificates
                      - certificates/status
                      - ingresses
                      - ingresses/status
                      - serverlessservices
                      - serverlessservices/status
                    - apiGroups:
                      - autoscaling.internal.knative.dev
                      apiVersions:
                      - v1alpha1
                      operations:
                      - CREATE
                      - UPDATE
                      scope: "*"
                      resources:
                      - metrics
                      - metrics/status
                      - podautoscalers
                      - podautoscalers/status
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true