kind: Namespace
apiVersion: v1
metadata:
  name: knative-serving
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  destination:
    namespace: knative-serving
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/acelinkio/empty.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          # $ must be escaped with by $$
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-core.yaml
            patches:
              - target:
                  kind: Namespace
                patch: |
                  $$patch: delete
                  kind: Namespace
                  metadata:
                    name: deletethis
              - target:
                  kind: ConfigMap
                  name: config-domain
                patch: |
                  $$patch: merge
                  kind: ConfigMap
                  metadata:
                    name: config-domain
                  data:
                    example.com: |
              - target:
                  kind: ConfigMap
                  name: config-network
                patch: |
                  $$patch: merge
                  kind: ConfigMap
                  metadata:
                    name: config-network
                  data:
                    ingress-class: kourier.ingress.networking.knative.dev
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
      name: webhook.serving.knative.dev
      jsonPointers:
        - /webhooks/0/rules
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
      name: validation.webhook.serving.knative.dev
      jsonPointers:
        - /webhooks/0/rules
  info:
    - name: workaround1
      value: "https://github.com/knative/serving/issues/13449#issuecomment-1676159959"