kind: Namespace
apiVersion: v1
metadata:
  name: kourier-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kourier-system
  namespace: argocd
spec:
  destination:
    namespace: kourier-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/acelinkio/empty.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          # $ must be escaped with by $$
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - https://github.com/knative/net-kourier/releases/download/knative-v1.11.1/kourier.yaml
            patches:
              - target:
                  kind: Namespace
                patch: |
                  $$patch: delete
                  kind: Namespace
                  metadata:
                    name: deletethis
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true