kind: Namespace
apiVersion: v1
metadata:
  name: kourier-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kourier-system
  namespace: argocd
spec:
  destination:
    namespace: kourier-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/acelinkio/empty.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          # $ must be escaped with by $$
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - https://github.com/knative/net-kourier/releases/download/knative-v1.11.1/kourier.yaml
            patches:
              - target:
                  kind: Namespace
                patch: |
                  $$patch: delete
                  kind: Namespace
                  metadata:
                    name: deletethis
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
# NOTE THIS IS FOR MANAGING knative-example RESOURCE
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knative-echo
  namespace: kourier-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/'
    nginx.ingress.kubernetes.io/upstream-vhost: 'knative-echo.knative-example.<path:stringreplacesecret#domain>'
    external-dns.custom/type: private
    external-dns.alpha.kubernetes.io/hostname: "knative.<path:stringreplacesecret#domain>"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
    - host: knative.<path:stringreplacesecret#domain>
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kourier-internal
                port:
                  number: 80