kind: Namespace
apiVersion: v1
metadata:
  name: kube-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.14.1
    helm:
      values: |
        autoDirectNodeRoutes: true
        bpf:
          masquerade: true
        cluster:
          name: home-cluster
          id: 1
        containerRuntime:
          integration: containerd
          socketPath: /var/run/k3s/containerd/containerd.sock
        endpointRoutes:
          enabled: true
        hubble:
          enabled: false
        ipam:
          mode: kubernetes
        ipv4NativeRoutingCIDR: "10.42.0.0/16"
        k8sServiceHost: "192.168.1.195"
        k8sServicePort: 6443
        kubeProxyReplacement: strict
        kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
        l2announcements:
          enabled: true
          # https://github.com/cilium/cilium/issues/26586
          leaseDuration: 120s
          leaseRenewDeadline: 60s
          leaseRetryPeriod: 1s
        loadBalancer:
          algorithm: maglev
          mode: dsr
        localRedirectPolicy: true
        operator:
          replicas: 1
          rollOutPods: true
        rollOutCiliumPods: true
        securityContext:
          privileged: true
        tunnel: disabled
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true