kind: Namespace
apiVersion: v1
metadata:
  name: longhorn-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.1
    helm:
      values: |
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
