---
kind: Namespace
apiVersion: v1
metadata:
  name: manyfold
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manyfold-redis
  namespace: manyfold
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: manyfold
        property: redis_password
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manyfold-redis
  namespace: argocd
spec:
  destination:
    namespace: manyfold
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: redis-ha
    repoURL: https://dandydeveloper.github.io/charts/
    targetRevision: 4.32.0
    helm:
      valuesObject:
        auth: true
        existingSecret: manyfold-redis
        authKey: password
        haproxy:
          enabled: true
        persistentVolume:
          enabled: true
          size: 2Gi
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true