---
kind: Namespace
apiVersion: v1
metadata:
  name: minio-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: operator
    repoURL: https://operator.min.io
    targetRevision: 5.0.15
    # helm:
    #   valuesObject:
    #     tenants: []
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

##
## reference.  should create a helm release just for tenant/buckets https://github.com/mcfio/home-cluster/blob/main/.archive/minio/release.yaml