kind: Namespace
apiVersion: v1
metadata:
  name: operator-lifecycle-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-lifecycle-manager
  namespace: argocd
spec:
  destination:
    namespace: operator-lifecycle-manager
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: olm
    repoURL: https://gitlab.com/api/v4/projects/29255838/packages/helm/stable
    targetRevision: v0.25.0
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
