---
kind: Namespace
apiVersion: v1
metadata:
  name: postgres
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: test00
  namespace: postgres
spec:
  teamId: acid
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "16"
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: cluster-01
  namespace: postgres
spec:
  teamId: acid
  volume:
    size: 1Gi
  numberOfInstances: 2
  preparedDatabases:
    authentik:
      defaultUsers: true
      extensions: {}
      schemas:
        data:
          defaultRoles: false
          defaultUsers: false
    vikunja:
      defaultUsers: true
      extensions: {}
      schemas:
        data:
          defaultRoles: false
          defaultUsers: false
  postgresql:
    version: "16"