---
kind: Namespace
apiVersion: v1
metadata:
  name: postgres
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: cluster-01
  namespace: postgres
spec:
  teamId: acid
  volume:
    size: 4Gi
  numberOfInstances: 2
  preparedDatabases:
    authentik:
      defaultUsers: true
      extensions: {}
      schemas:
        # still uses public schema...
        # https://github.com/goauthentik/authentik/issues/9212        
        public:
          defaultRoles: false
          defaultUsers: false
    vikunja:
      defaultUsers: true
      extensions: {}
      schemas:
        public:
          defaultRoles: false
          defaultUsers: false
  postgresql:
    version: "16"
    parameters:
      password_encryption: scram-sha-256
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster-01.postgres.authentik.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 60s
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-owner-user.cluster-01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: cluster-01.postgres.authentik.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: cluster-01.postgres.authentik.owner
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster-01.postgres.vikunja.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 60s
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: vikunja-owner-user.cluster-01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: cluster-01.postgres.vikunja.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: cluster-01.postgres.vikunja.owner
          property: password