---
kind: Namespace
apiVersion: v1
metadata:
  name: postgres
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: cluster01
  namespace: postgres
spec:
  teamId: acid
  volume:
    size: 4Gi
    storageClass: longhorn
  numberOfInstances: 2
  preparedDatabases:
    authentik:
      defaultUsers: true
      extensions: {}
      schemas:
        # still uses public schema...
        # https://github.com/goauthentik/authentik/issues/9212        
        public:
          defaultRoles: false
          defaultUsers: false
    miniflux:
      defaultUsers: true
      extensions: {}
      schemas:
        data:
          defaultRoles: false
          defaultUsers: false
    ryot:
      defaultUsers: true
      extensions: {}
      schemas:
        data:
          defaultRoles: false
          defaultUsers: false
    vikunja:
      defaultUsers: true
      extensions: {}
      schemas:
        # still uses public schema...
        # https://community.vikunja.io/t/postgres-database-has-error-pq-relation-tasks-does-not-exist/1333
        public:
          defaultRoles: false
          defaultUsers: false
  postgresql:
    version: "16"
    parameters:
      password_encryption: scram-sha-256
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster01.authentik.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-owner-user.cluster01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster01.authentik.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster01.authentik.owner
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster01.miniflux.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: miniflux-owner-user.cluster01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster01.miniflux.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster01.miniflux.owner
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster01.ryot.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: ryot-owner-user.cluster01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster01.ryot.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster01.ryot.owner
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster01.vikunja.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: vikunja-owner-user.cluster01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster01.vikunja.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster01.vikunja.owner
          property: password
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: cluster02
  namespace: postgres
spec:
  teamId: acid
  volume:
    size: 2Gi
    storageClass: longhorn
  numberOfInstances: 1
  preparedDatabases:
    publictestdb:
      defaultUsers: true
      extensions: {}
      schemas:      
        public:
          defaultRoles: false
          defaultUsers: false
    datatestdb:
      defaultUsers: true
      extensions: {}
      schemas:
        data:
          defaultRoles: false
          defaultUsers: false
  postgresql:
    version: "16"
    parameters:
      password_encryption: scram-sha-256
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster02.publictestdb.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: publictestdb-owner-user.cluster02.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster02.publictestdb.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster02.publictestdb.owner
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster02.datatestdb.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: datatestdb-owner-user.cluster02.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster02.datatestdb.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster02.datatestdb.owner
          property: password