---
kind: Namespace
apiVersion: v1
metadata:
  name: rabbitmq-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq-operator
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: bitnamicharts/rabbitmq-cluster-operator
    repoURL: registry-1.docker.io
    targetRevision: 4.3.1
    helm:
      valuesObject:
        msgTopologyOperator:
          enabled: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true