---
kind: Namespace
apiVersion: v1
metadata:
  name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: cluster01
  namespace: rabbitmq
spec:
  replicas: 3
  persistence:
    storageClassName: longhorn
    storage: 2Gi
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: cluster01-kyoo
  namespace: rabbitmq
spec:
  name: kyoo
  rabbitmqClusterReference:
    name: cluster01
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: cluster01-user0
  namespace: rabbitmq
spec:
  tags:
    - administrator
  rabbitmqClusterReference:
    name: cluster01
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: cluster01-user0-permission0
  namespace: rabbitmq
spec:
  vhost: "/"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  userReference:
    name: cluster01-user0
  rabbitmqClusterReference:
    name: cluster01