---
kind: Namespace
apiVersion: v1
metadata:
  name: reloader
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.0.104
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
