---
kind: Namespace
apiVersion: v1
metadata:
  name: s3
## wait for next release of minio operator 
## where their tenant configuration is not bad
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tenant0
#   namespace: argocd
# spec:
#   destination:
#     namespace: s3
#     server: https://kubernetes.default.svc
#   project: homelab
#   source:
#     chart: tenant
#     repoURL: https://operator.min.io
#     targetRevision: 5.0.14
#     helm:
#       valuesObject:
#         tenant:
#           name: tenant0
#           configuration:
#             name: teant0
#   syncPolicy:
#     automated:
#       allowEmpty: true
#       prune: true
#       selfHeal: true
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: teant0
#   namespace: s3
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# spec:
#   refreshInterval: "5m"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: 1password
#   target:
#     creationPolicy: Owner
#     template:
#       data:
#         config.env: |-
#           export MINIO_ROOT_USER={{ .tenant0_rootuser | toString }}
#           export MINIO_ROOT_PASSWORD={{ .tenant0_rootpassword | toString }}
#   data:
#     - secretKey: tenant0_rootuser
#       remoteRef:
#         key: s3
#         property: tenant0_rootuser
#     - secretKey: tenant0_rootpassword
#       remoteRef:
#         key: s3
#         property: tenant0_rootpassword