---
kind: Namespace
apiVersion: v1
metadata:
  name: s3
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  labels:
    app: minio
  name: minio1
  namespace: s3
spec:
  credsSecret:
    name: minio1-secret
  image: minio/minio:RELEASE.2021-10-06T23-36-31Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
    - servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard
      volumesPerServer: 4
  requestAutoCert: true
  s3:
    bucketDNS: false
  subPath: /data