kind: Namespace
apiVersion: v1
metadata:
  name: sandbox
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo-knative
  namespace: sandbox
spec:
  template:
    spec:
      containers:
      - image: ealen/echo-server
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo-knative
  namespace: sandbox
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: echo-knative.sandbox.<path:stringreplacesecret#domain>
      recordType: A
      targets:
        - "192.168.1.50"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
# ---
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: httpbin-knative
#   namespace: sandbox
# spec:
#   template:
#     spec:
#       containers:
#       - image: kong/httpbin
#         ports:
#           - containerPort: 80