kind: Namespace
apiVersion: v1
metadata:
  name: test1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
spec:
  ingressClassName: ingress-nginx-external
  rules:
    - host: test1.<path:stringreplacesecret#domain>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test1
                port:
                  number: 80