kind: Namespace
apiVersion: v1
metadata:
  name: test1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-inline
  namespace: argocd
spec:
  destination:
    namespace: test1
    server: https://kubernetes.default.svc
  project: homelab
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: .
    plugin:
      name: kustomize-inline
      env:
        - name: KUSTOMIZATION_YAML
          value: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            metadata:
              name: knative
            namespace: test1  
            resources:
              - https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-deployment.yaml
              - https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-svc.yaml
            patches:
              - target:
                  kind: Deployment
                  name: guestbook-ui
                patch: |-
                  - op: replace
                    path: /spec/template/spec/containers/0/ports/0/containerPort
                    value: 443
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true