kind: Namespace
apiVersion: v1
metadata:
  name: test1
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: knative
  namespace: test1
namespace: test1  
resources:
- https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-core.yaml
patches:
- target:
    kind: Namespace
  patch: |-
    $patch: delete
    kind: Namespace
    metadata:
      name: kdelete