---
kind: Namespace
apiVersion: v1
metadata:
  name: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crds
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: traefik-crds
    repoURL: https://traefik.github.io/charts
    targetRevision: 1.6.0
    helm:
      valuesObject:
        traefik: true
        gatewayAPI: false
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 35.0.0
    helm:
      skipCrds: true
      valuesObject:
        ingressClass:
          enabled: false
        experimental:
          enabled: false
        gateway:
          enabled: false
        gatewayClass:
          enabled: true
        providers:
          # https://doc.traefik.io/traefik-hub/api-gateway/reference/install/providers/ref-provider-crd#configuration-example
          kubernetesCRD:
            enabled: true
            allowEmptyServices: true
            nativeLBByDefault: true
            throttleDuration: 2s
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
            #experimentalChannel: true
        ports:
          web:
            port: 80
          websecure:
            port: 443
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true