---
kind: Namespace
apiVersion: v1
metadata:
  name: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 34.5.0
    helm:
      valuesObject:
        ingressClass:
          enabled: false
        experimental:
          enabled: false
        gateway:
          enabled: false
        gatewayClass:
          enabled: true
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
            #experimentalChannel: true
        ports:
          web:
            port: 80
          websecure:
            port: 443
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true