---
kind: Namespace
apiVersion: v1
metadata:
  name: volsync-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
spec:
  destination:
    namespace: volsync-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: volsync
    repoURL: ghcr.io/home-operations/charts-mirror
    targetRevision: 0.12.1
    helm:
      valuesObject:
        manageCRDs: true
        replicaCount: 2
        image:
          repository: ghcr.io/home-operations/volsync
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
