---
kind: Namespace
apiVersion: v1
metadata:
  name: zot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zot
  namespace: zot
data:
  # default configuration
  config.json: |-
    {
      "storage":{
          "rootDirectory":"/var/lib/registry"
      },
      "http":{
          "address":"0.0.0.0",
          "port":"5000",
          "compat": ["docker2s2"]
      },
      "log":{
          "level":"debug"
      },
      "extensions": {
        "search": {
            "enable": true,
            "cve": {
                "updateInterval": "2h"
            }
        },
        "ui": {
            "enable": true
        },
        "mgmt": {
          "enable": true
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot
  namespace: zot
  labels:
    app.kubernetes.io/instance: zot
    app.kubernetes.io/name: zot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zot
      app.kubernetes.io/name: zot
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zot
        app.kubernetes.io/name: zot
    spec:
      containers:
        - env:
            - name: exampleenv
              value: "myexample"
          name: zot
          image: ghcr.io/project-zot/zot:v2.1.1
          ports:
            - name: zot
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: zot-registry
              mountPath: /var/lib/registry
      volumes:
        - name: zot-registry
          persistentVolumeClaim:
            claimName: zot-storage
        - name: config
          configMap:
            name: zot
            items:
              - key: config.json
                path: config.json
  strategy:
    type: Recreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: zot
  name: zot-storage
  namespace: zot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: zot
    app.kubernetes.io/name: zot
  name: zot
  namespace: zot
spec:
  ports:
    - name: zot
      port: 5000
      protocol: TCP
      targetPort: zot
  selector:
    app.kubernetes.io/instance: zot
    app.kubernetes.io/name: zot
  type: ClusterIP
