kind: Namespace
apiVersion: v1
metadata:
  name: testns
---
apiVersion: v1
kind: Service
metadata:
  name: cyberchef
  namespace: testns
  labels:
    app.kubernetes.io/instance: cyberchef
    app.kubernetes.io/name: cyberchef
    app.kubernetes.io/service: cyberchef
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: cyberchef
    app.kubernetes.io/name: cyberchef