---
kind: Namespace
apiVersion: v1
metadata:
  name: kyoo
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso
  namespace: kyoo
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: sso
        property: kyoo_client_id
    - secretKey: clientSecret
      remoteRef:
        key: sso
        property: kyoo_client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: misc
  namespace: kyoo
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: kyoo_apikeys
      remoteRef:
        key: kyoo
        property: kyoo_apikeys
    - secretKey: tmdb_apikey
      remoteRef:
        key: kyoo
        property: tmdb_apikey
    - secretKey: tvdb_apikey
      remoteRef:
        key: kyoo
        property: tvdb_apikey
    - secretKey: tvdb_pin
      remoteRef:
        key: kyoo
        property: tvdb_pin
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kyoo
#   namespace: argocd
# spec:
#   destination:
#     namespace: kyoo
#     server: https://kubernetes.default.svc
#   project: homelab
#   source:
#     chart: kyoo
#     repoURL: ghcr.io/zoriya/helm-charts
#     targetRevision: 4.7.1
#     helm:
#       valuesObject:
#         global:
#           meilisearch:
#             kyoo_back:
#               existingSecret: kyoo-back
#           postgres:
#             kyoo_back:
#               host: cluster04.postgres
#               kyoo_migrations:
#                 existingSecret: kyoo-back
#               kyoo_back:
#                 existingSecret: kyoo-back
#             kyoo_transcoder:
#               host: cluster04.postgres
#               sslmode: require
#               kyoo_transcoder:
#                 existingSecret: kyoo-transcoder
#           rabbitmq:
#             host: cluster01.rabbitmq
#             kyoo_autosync:
#               existingSecret: kyoo-autosync
#             kyoo_back:
#               existingSecret: kyoo-back
#             kyoo_matcher:
#               existingSecret: kyoo-matcher
#             kyoo_scanner:
#               existingSecret: kyoo-scanner
#         contentdatabase:
#           tmdb:
#             existingSecret: misc
#           tvdb:
#             existingSecret: misc
#         kyoo:
#           address: https://kyoo.bitey.life
#           apikey:
#             existingSecret: misc
#           oidc_providers:
#             - name: Authentik
#               logo: https://avatars.githubusercontent.com/u/82976448?s=48&v=4
#               existingSecret: sso
#               clientIdKey: clientId
#               clientSecretKey: clientSecret
#               scope: "email openid profile"
#               authMethod: ClientSecretBasic
#               authorizationAddress: https://auth.bitey.life/application/o/authorize/
#               tokenAddress: https://auth.bitey.life/application/o/token/
#               profileAddress: https://auth.bitey.life/application/o/userinfo/
#         media:
#           volumes:
#             - name: media
#               nfs:
#                 server: "192.168.1.179"
#                 path: /spin0/media/movies
#   syncPolicy:
#     automated:
#       allowEmpty: true
#       prune: true
#       selfHeal: true
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kyoo-public
  namespace: kyoo
  annotations:
    external-dns.custom/type: public
spec:
  endpoints:
    - dnsName: kyoo.bitey.life
      recordType: CNAME
      targets:
        - ingress.bitey.life
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kyoo-private
  namespace: kyoo
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: kyoo.bitey.life
      recordType: CNAME
      targets:
        - intgw.bitey.life
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: kyoo
#   namespace: kyoo
# spec:
#   parentRefs:
#     - name: internal
#       namespace: gateway
#       sectionName: https
#     - name: external
#       namespace: gateway
#       sectionName: https
#   hostnames:
#     - "kyoo.bitey.life"
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /api
#       backendRefs:
#         - name: kyoo-back
#           port: 5000
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       backendRefs:
#         - name: kyoo-front
#           port: 8901
