---
kind: Namespace
apiVersion: v1
metadata:
  name: crossplane-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 2.1.4
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: tf-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            args:
              - -d
              - --poll=15m
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-opentofu
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: xpkg.upbound.io/upbound/provider-opentofu:v1.0.1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: tf-config